### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jkburges** [jkburges/wreck#2]
* [x] logging
* [x] match based on HTTP method
* [x] delays
* [ ] factor out configuration in to own class
* [x] default response 500
* [ ] match based on block
* [ ] different distributions types
* [ ] tests for main logic (plus refactoring?)
* [ ] dropping connections
* [ ] hangs
* [ ] repeatable behaviour (seeding)
